name: Update Lambda Layer

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  update_lambda_layer:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Build and Run generate-layer image
      - name: Build Lambda_Layer through the docker image
        run: |
          cd generate-layer/scripts/
          chmod +x runner.sh  # Ensure the script is executable
          ./runner.sh 
      
          #Step 3: Upload the lambda_function.py file to S3 bucket
      - name: Uploading lambda function to S3
        run: |
          pwd
          ls -l
          echo "Zipping artifacts and pushing to S3..."
          mkdir lambda_artifacts
          zip lambda_artifacts/lambda_artifact.zip lambda_function.py
          aws s3 sync ./lambda_artifacts s3://momotaropackage/
          
      #step 4: Update the layer packages and lambda function
      - name: updating lambda handler from s3
        run: |
          pwd
          ls -l
          echo "Updating lambda function..."
          aws lambda update-function-code --function-name "MomotaroCode" --s3-bucket "momotaropackage" --s3-key "lambda_artifact.zip"
          echo "Lambda function successfully updated"
     
      #step 5: Upion
      - name: updating layer from s3
        run: |
          pwd
          ls -l
          echo "pushing latest layers package..."
          aws lambda publish-layer-version --layer-name "momotaro-layer" --content '{"S3Bucket":"momotaropackage","S3Key":"python.zip","S3ObjectVersion":"null"}' --compatible-runtimes "python3.11"
          echo "Lambda function successfully updated"

      #step 6: Update the layer with the latest package
      - name: updating lambda configuration
        run: |
          pwd
          ls -l
          echo "Updating layers..."
          aws lambda update-function-configuration --function-name MomotaroCode --layers "arn:aws:lambda:ca-central-1:798965869505:layer:momotaro-layer"
          echo "Lambda function successfully updated"   
                  
                
      # Step 5: Initialize Terraform
      - name: Initialize Terraform
        run: |
          terraform fmt
          terraform init -upgrade
          terraform apply -auto-approve
