name: Update Lambda Layer

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  update_lambda_layer:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Build and Run generate-layer image
      - name: Build Lambda_Layer image
        run: |
          cd generate-layer/scripts/
          chmod +x runner.sh  # Ensure the script is executable
          ./runner.sh 
        # You may need to log in to a Docker registry here
      - name: Debug
        run: |
          cd generate-layer/scripts/
          pwd
          ls -l
          aws s3 cp python.zip s3://momotaropackage/

       # Step 1: Initialize Terraform
      - name: Initialize Terraform
        run: |
          terraform fmt
          terraform init -upgrade
          terraform apply -auto-approve
  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:  ${{ secrets.AWS_REGION }}

  